[HTTP]
DNS = "poller.q"
CoreDNS = "core.q"
ListenAddress = "0.0.0.0:8448"
TLSCertPath = "/var/lib/q-scheduler/cert.pem"
TLSKeyPath = "/var/lib/q-scheduler/key.pem"

[Database]
Path = "/var/lib/q-scheduler/database.sqlite3"

[Scheduler]
Worker = 50